# Build script
init:
  - git config --global core.autocrlf true

image: Visual Studio 2022

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor" --verbosity=diagnostic

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - develop
    - master
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
- tools -> recipe.cake
- node_modules -> package.json
- packages -> '**/*.csproj'
