# Build script
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: Get-ChildItem -Path "C:\Program Files (x86)\Microsoft SDKs\TypeScript\*" -Include tsc.exe,tsc.js -Recurse | Rename-Item -NewName {$_.name -replace "tsc","tsc1"}
  - ps: .\build.ps1 -Target "AppVeyor"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - develop
    - master
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
- tools -> recipe.cake
- node_modules -> package.json
- packages -> '**/*.csproj'